version: 2
jobs:
  test:
    docker:
      - image: golang:1.10-stretch
    environment:
      GOROOT: ""
      GOPATH: "${HOME}/.go_project"
      PATH: "${GOPATH}/bin:${PATH}"
      IMPORT_PATH: "github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
    steps:
      - run:
          name: Install prerequired packges
          command: |
            /usr/bin/apt update
            /usr/bin/apt install software-properties-common python-software-properties
            /usr/bin/add-apt-repository -y ppa:masterminds/glide
            /usr/bin/apt update
            /usr/bin/apt install -y librrd-dev glide
            mkdir -p ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}
            ln -s ${HOME}/${CIRCLE_PROJECT_REPONAME} ${BUILD_PATH}
            glide i
      - run:
          name: Run tests
          command: |
            go test
  deploy:
    docker:
      - image: golang:1.10-stretch
    environment:
      GOROOT: ""
      GOPATH: "${HOME}/.go_project"
      PATH: "${GOPATH}/bin:${PATH}"
      IMPORT_PATH: "github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
    steps:
      - run:
          name: Install prerequired packges
          command: |
            /usr/bin/apt install software-properties-common python-software-properties
            /usr/bin/add-apt-repository -y ppa:masterminds/glide
            /usr/bin/apt update
            /usr/bin/apt install -y librrd-dev glide
            mkdir -p ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}
            ln -s ${HOME}/${CIRCLE_PROJECT_REPONAME} ${BUILD_PATH}
            glide i
      - checkout
      - run:
          name: Deploy
          tag: /v[0-9]+(\.[0-9]+)+/
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            gox -osarch "linux/amd64" -ldflags "-X main.Version=$BUILD_VERSION -X main.BuildDate=$BUILD_DATE" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
            gzip dist/*
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $(git describe --tags) dist/
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
            branches:
              ignore: /.*/   
